version: "3.9"

services:
  mongo:
    image: mongo:6.0-jammy
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: khsu
    volumes:
      - mongo_data:/data/db

  bot:
    container_name: khsu_bot
    build: .   # можно оставить для локальной сборки
    image: igorushakov111/khsu-bot:latest
    depends_on:
      - mongo
    restart: unless-stopped
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  mongo_data:
