name: CI Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Write .env
        run: |
          printf "%s" "${{secrets.ENV_FILE}}" > .env
      - name: Run tests
        run: npm start
