name: CI Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: npm install

      - name: Write .env
        run: |
          printf "%s" "${{secrets.ENV_FILE}}" > .env

      - name: Build and run with docker compose and start
        run: |
          docker compose up --build 
